#!/bin/bash

grep_version() {
	echo "$(cat $1 | grep $2 | egrep -Eo "([0-9]{1,}\.)+[0-9]{1,}")"
}

GODOT_SHARP_EXTRAS="$(grep_version $2 GodotSharpExtras)"
NEWTONSOFT_JSON="$(grep_version $2 Newtonsoft.JSON)"
SYSTEM_IO_COMPRESSION="$(grep_version $2 System.IO.Compression)"
IMAGE_SHARP="$(grep_version $2 Sixlabors.ImageSharp)"

echo "Generating Versions:"
echo "  Godot Manager: from application/config/version"
echo "  GodotSharpExtras: $GODOT_SHARP_EXTRAS"
echo "  Newtonsoft.JSON: $NEWTONSOFT_JSON"
echo "  System.IO.Compression: $SYSTEM_IO_COMPRESSION"
echo "  Sixlabors.ImageSharp: $IMAGE_SHARP"
echo

cat > "$3" <<'EOF'
using Godot;

public static partial class VERSION {
	public static string GodotManager =>
		ProjectSettings.GetSetting("application/config/version", "0.0.0").AsString();

	public static string Channel = "release";
EOF
echo "	public static string GodotSharpExtras = \"$GODOT_SHARP_EXTRAS\";" >> $3
echo "	public static string NewtonsoftJSON = \"$NEWTONSOFT_JSON\";" >> $3
echo "	public static string SystemIOCompression = \"$SYSTEM_IO_COMPRESSION\";" >> $3
echo "	public static string ImageSharp = \"$IMAGE_SHARP\";" >> $3
echo "}" >> $3

echo "Generation completed, stored in file $3"
